---
- hosts: all
  vars:
  - httpd_packages:
      - python3-mod_wsgi
      - httpd
  - apache_test_message: 'http test'
  - item: 'httpd.conf'
  tasks:
       - name: "httpd_packages"
         yum: name={{ httpd_packages  }} state=latest
       - name: "apache_test_message"
         shell: echo {{ apache_test_message }} > /var/www/html/index.html
       - lineinfile:
             path: /etc/httpd/conf/{{ item }}
             regexp: '^MaxKeepAliveRequests 100'
             line: 'MaxKeepAliveRequests 115'
  handlers:
       - name: restart httpd
         service: name=httpd state=restarted enabled=yes
